### PR TITLE
Modifications to allow api to proxy via a docker container

### PR DESCRIPTION
**Pull request by pkbfs**
Hi,

This is in reference to the feature request I made here

https://github.com/zaproxy/zaproxy/issues/5473

Please bear with me I am new to git and github.

Cheers
pkbfs

### CODE REVIEW

**Comment by thc202** [comment]
The existing logic looks right to me, what needs to be changed is `BuildZapRequestUrl` to use the `zap` domain/host?

**Comment by pkbfs** [comment]
In that case zapAddress and zapPort variables are being used for two different purposes.

1. To store the address and port of the zap daemon which in my example would be
    zapAddress : myzapdockercontainer.uksouth.azurecontainer.io
    zapPort : 8090
    and are variables

2. To store the api domain and port - 'zap' and 80 -- which are constants

So two new constants are needed - zapAPIDomain and zapAPIPort being the values 'zap' and 80?

**Comment by thc202** [comment]
That looks right to me.

**Comment by gmaran23** [comment]
Good code and good contribution. Thanks for improving OWASP ZAP.

**Pull request merged**
