### PR TITLE
Update API to 2.12.0

### PR DESCRIPTION
**Pull request by njmulsqb**
Update the core and client APIs to version 2.12.0

### CODE REVIEW

**Comment by njmulsqb** [comment]
Hi @gmaran23,
I tried building the project using `dotnet build` but since this is built with .NET Framework 4.5 so it failed. I am using macOS, and I couldn't find a binary for it, https://www.microsoft.com/en-us/download/details.aspx?id=30653
I am running the latest version of dotnet, is there any workaround to get the .dll generated?
Also, should we consider upgrading the dotnet version since 4.5 is outdated and unsupported now?

**Comment by gmaran23** [comment]
Thanks for trying. 
We will have to upgrade to at least .net 4.7. 

Please allow sometime, we will get the dlls built on a windows environment.

**Comment by njmulsqb** [comment]
@gmaran23, did you get the chance to build the DLLs? 
If the schedule looks tight, let me know if I can help with it somehow.

**Comment by gmaran23** [comment]
@njmulsqb 
Thanks for offering to help.

Would you be able to test the ZAP's Java Client API with the ZAP version 2.12.0?

The 'tags' that are introduced in the alerts seem to be breaking the Dot Net API, so it requires an update. It would help to know how the Java API client handles this situation.

The structure of an alert set with 2.10.0 was like below:

```
<alerts type=list>
<alert type=set>
<name>xxxx</name>
<id>1</id>
.
.
</alert>
<alert type=set>
<name>xxxx</name>
<id>2</id>
.
.
</alert>
```

The structure of an alert in 2.11.0, and 2.12.0 has changed to:

```
<alerts type=list>
<alert type=set>
<name>xxxx</name>
<id>1</id>
<tags type=list>
<tag type=set>
<key>OWASPTOP12017</key>
<value>https://owasp.org/xxxxx</value>
<tag>
<tags>
.
.
</alert>
<alert type=set>
<name>xxxx</name>
<id>2</id>
<tags type=list>
<tag type=set>
<key>OWASPTOP12017</key>
<value>https://owasp.org/xxxxx</value>
<tag>
<tags>
.
.
</alert>
```


Because of this change, in the Dot Net API, when we are expecting an APIResponseElement (which is a dictionary of string, string), we are getting a APIResponseList (because of the new item called tags which is a list). Here's the line of code that is affected by this change - https://github.com/zaproxy/zap-api-dotnet/blob/master/src/OWASPZAPDotNetAPI/OWASPZAPDotNetAPI/ApiResponseSet.cs#L55


Here's the Java APi's client code - https://github.com/zaproxy/zap-api-java/blob/main/subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ApiResponseSet.java#L60

It appears that the Java API client code is not updated to handle the above scenario. It would help if you are able to test whether the java api client works well in processing the alerts that have the [new tag information for a vulnerability](https://www.zaproxy.org/alerttags/).

**Comment by thc202** [comment]
The Java client was not updated because it does not need to, the API responses are handled generically not assuming that they have specific type(s). The .NET client should do the same.

For the record there's an issue for that zaproxy/zap-api-dotnet#17.

**Comment by gmaran23** [comment]
Thanks. I took a second look, and the Java client seems to have a generic implementation as well. 

I will get an update done soon.

**Review by gmaran23 — APPROVED** [review]
Looks alright. Proceeding to merge.

**Comment by gmaran23** [comment]
@njmulsqb Thanks for generating the api client files, and submitting a PR.

The nuget packages are updated as well.

Dlls upgraded to .Net Framework 4.8.

**Comment by thc202** [comment]
Note that there are API endpoints that no longer exist (e.g. `ImportLogFiles`), IMO those should have been removed since they will no longer work with 2.12.x.

**Comment by njmulsqb** [comment]
> @njmulsqb Thanks for generating the api client files, and submitting a PR.
> 
> The nuget packages are updated as well.
> 
> Dlls upgraded to .Net Framework 4.8.

Should we now move towards upgrading it to the latest .NET version as per https://github.com/zaproxy/zap-api-dotnet/issues/16 ?

**Comment by gmaran23** [comment]
> Note that there are API endpoints that no longer exist (e.g. `ImportLogFiles`), IMO those should have been removed since they will no longer work with 2.12.x.

@thc202 Is there a way you'd recommend to remove the API endpoints that not longer exist? Like how we automatically generate API files.

**Comment by gmaran23** [comment]
> > @njmulsqb Thanks for generating the api client files, and submitting a PR.
> > The nuget packages are updated as well.
> > Dlls upgraded to .Net Framework 4.8.
> 
> Should we now move towards upgrading it to the latest .NET version as per [zaproxy/zap-api-dotnet#16](https://github.com/zaproxy/zap-api-dotnet/issues/16) ?

The latest version of .Net Framework is 4.8, and the dot net api is updated to 4.8.

If you are referring to .Net 6 or .Net 7 (which are cross platform), then that needs a bit of significant effort, and we will get it done soon.

As for now, the current update uses .Net Framework 4.8 which is still supported.

**Comment by njmulsqb** [comment]
@gmaran23 Yeah I understand that 4.8 is latest of .NET and is supported. I am talking about shifting to .NET 7, again I understand that lots of effort will go into this but it will ultimately be required sooner or later, plus it will make our API cross platform too. 
If you can give me the pointers on what needs to be changed I can probably work on this and get this done :)

**Comment by gmaran23** [comment]
Thank you for offering to help. I will open a new issue for .NET cross platform upgrade.

**Comment by thc202** [comment]
https://github.com/zaproxy/zap-api-dotnet/pull/15#issuecomment-1461306775

That needs to be done manually, the following endpoints can be removed: `ImportLogFiles`, `Importurls`, and `LocalProxies`.

**Pull request merged**
